server:
  port: 8889

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AbdelkaderHassani/config-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost/eureka