spring:
  application:
    name: auth-api  # Nom de l'application
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root  # Utilisateur pour se connecter à la base de données
    password: Abdelkader1919  # Mot de passe directement défini ici
  jpa:
    hibernate:
      ddl-auto: update  # Utilisez 'update' uniquement en développement
    open-in-view: false  # Améliore la gestion de la session Hibernate
  logging:
    level:
      root: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Niveau de log de SQL pour débogage

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b  # Clé secrète pour JWT
    expiration-time: 3600000  # Durée d'expiration du token JWT en millisecondes (1h)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # URL de votre serveur Eureka

server:
  port: 8005  # Port sur lequel le service auth-api va être exposé
