spring:
  application:
    name: commande-service
  datasource:
    url: jdbc:mysql://localhost:3306/commandesdb  # Correction de l'URL
    username: root
    password: Abdelkader1919
  jpa:
    hibernate:
      ddl-auto: update
  logging:
    level:
      root: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
