spring:
  application:
    name: livre-service
  datasource:
    url: jdbc:mysql://localhost:3306/librairiedb  # Base de données pour le service livre
    username: root
    password: Abdelkader1919
  jpa:
    hibernate:
      ddl-auto: update
  logging:
    level:
      root: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
